### ISSUE TITLE
[BUG] Using AzureOpenAI provider does not show token usage/price

### ISSUE THREAD

**Issue by Dannyjelll** [truera/trulens#1152] opened 2024-05-23 12:46 UTC
**Bug Description**
Cost/Token Usage display does not work with AzureOpenai Provider

**To Reproduce**
Try to evaluate a RAG application using the AzureOpenai provider for any metric like groundedness or answer relevance

**Expected behavior**
It should display the Token usage/price

**Relevant Logs/Tracebacks**
I implemented both a custom retriever and one using Trullama. In both cases, I used AzureOpenAI as LLM.:

from trulens_eval.feedback.provider.openai import AzureOpenAI as fAzureOpenai
openai_provider = fAzureOpenai(deployment_name="chat_test")

then 
f_qa_relevance = (
    Feedback(
        openai_provider.relevance_with_cot_reasons,
        name = "Answer Relevance",
    )
    .on(Select.RecordCalls.retrieve.args.query)
    .on_output()
)

and so on. The usage is always 0.

**Environment:**
 - OS: Windows 11 and Archlinux both tested
 - python 3.10.13
 - Trulens 0.28.2

**Additional context**
none

**Comment by sfc-gh-jreini** [comment] 2024-06-09 02:27
@sfc-gh-dhuang can you take a look at this?

**Comment by sfc-gh-dkurokawa** [comment] 2024-09-12 16:18
This is a duplicate of https://github.com/truera/trulens/issues/1342 so closing in favor of that which I saw first (though came later haha).

**Closed by sfc-gh-dkurokawa** 2024-09-12 16:18 UTC
Labels: bug
